name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9.4'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        # If you have other dependencies, install them here
        # pip install -r requirements.txt

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9.4'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        # If your project has specific dependencies for testing, install them here
        # pip install -r requirements.txt
    - name: Run tests
      run: pytest
